### ISSUE TITLE
Please use web fonts

### ISSUE THREAD

**Issue by natewind** [slikts/js-equality-game#1]
![image](https://user-images.githubusercontent.com/30814650/45308446-280d1500-b52a-11e8-8ec7-b0acafb98392.png)

[CSS Web Fonts | W3Schools](https://www.w3schools.com/css/css3_fonts.asp)

**Comment by natewind** [comment]
What do you mean, there isn’t a simple fix?
What’s the ~~excuse~~ reason not to use @font-face? Usually, there is none.
Relying on the user having a certain font is kinda strange.

**Comment by slikts** [comment]
I mean that there isn't a simple fix; there's no uniform browser support for color font formats, and I'd also need to make a subset font, and it's unclear if the tools for making subset fonts even support color fonts. A more realistic solution would be to use images, but I'd prefer to use emojis.

**Comment by slikts** [comment]
There should now be .svg image fallbacks if emojis are not supported (Ctrl+F5 is probably needed to test).

**Comment by Leodau** [comment]
Ya, .svg emojis could be a good idea right?

**Comment by slikts** [comment]
.svg fallbacks are already implemented, but the detection for emoji support seems to also detect partial support, so the fallbacks aren't enabled in that case, even though it doesn't look completely right. I've posted a [question][so] on SO about it. My current idea is that maybe the detection could be applied to the specific emojis being shown.

[so]: https://stackoverflow.com/questions/52365231/how-to-reliably-detect-color-emoji-support-in-browsers
