### ISSUE TITLE
[] == 0, [[]] == 0

### ISSUE THREAD

**Issue by CodeSmith32** [slikts/js-equality-game#14]
Not sure if this is specific to Chrome, or just a general deviance from what's been stated in the spec, or just something the game got wrong, but:

![image](https://user-images.githubusercontent.com/21373557/57989327-328f8f00-7a67-11e9-8088-106a0ab55ec5.png)

Yet,

![image](https://user-images.githubusercontent.com/21373557/57989338-4a671300-7a67-11e9-8615-a99b6d231c38.png)

(p.s., yeah, I kinda cheated on a few ;-)

p.p.s., You may also consider showing some other horrible truths, like,

![image](https://user-images.githubusercontent.com/21373557/57989421-60c19e80-7a68-11e9-90bd-894f91839d47.png)

**Comment by slikts** [comment]
The result in the screenshot is correct; it shows that the `[] == 0` and `[[]] == 0` cells should have been flagged.

Adding `{} == '[object Object]'` is an interesting idea; I might do that, thanks.

**Comment by CodeSmith32** [comment]
Gosh, right, I interpreted that wrong.. I thought for sure I had flagged them, and it was marking me wrong :-)
Thanks!
