### ISSUE TITLE
132% wrong?

### ISSUE THREAD

**Issue by ruslanegorov** [slikts/js-equality-game#2]
![image](https://user-images.githubusercontent.com/43210596/45568771-2a42dc80-b866-11e8-9852-1848cedd4cf2.png)

**Comment by slikts** [comment]
The sidebar explains this; marking empty cells count as a miss, so you missed 11 - 2 + 20 times, so there's more misses than possible correct answers (29/22 = 1.32).

**Comment by slikts** [comment]
I suppose I should explicate the formula in the UI.

**Comment by slikts** [comment]
Formula added to UI.
