### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by Shuunen** [slikts/js-equality-game#5]
Hi there 😄 

Thanks for your projet, really cool to explains dangers of double equals to people that never use triple,

Would be great to translate it, I can contribute to add French translations 👍

**Comment by slikts** [comment]
I've added support for translations; if you're still interested, the template is here: https://github.com/slikts/js-equality-game/blob/master/src/translations/en-US.json

The translation then needs to be added here (I can help with this): https://github.com/slikts/js-equality-game/blob/master/src/translationData.js

It's fine to just post the translated JSON in the comments.

**Comment by Shuunen** [comment]
I'm on it 😄 I did 30% and my PR should come soon

**Comment by Shuunen** [comment]
here is it : #7
